version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - configuration: Release
    platform: Win32
install:
  - git submodule -q update --init --recursive
  - cd ..
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - set cmake_38_url="https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip"
  - appveyor DownloadFile %cmake_38_url% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  - cd ..
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg integrate install
  - cd ..
  - cd C:\projects\get-nominatim-info
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017" "-DCMAKE_TOOLCHAIN_FILE=C:\projects\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - cmake --build . --target install
